export type { 
  Animal,
  AnimalStatus,
  AnimalGender,
  AnimalSpecies,
  AnimalBreed,
  GeneticTraitScores,
  GeneticProfile,
  PedigreeNode,
  PedigreeTree,
  HealthEventType,
  HealthEvent,
  BreedingMethod,
  BreedingOutcome,
  BreedingEvent,
  TreatmentProtocol,
  VaccinationSchedule,
  FeedType,
  FeedConsumption,
  FeedInventory,
  EconomicEvent,
  FinancialRecord,
  FeedlotReport,
  TaskPriority,
  TaskCategory,
  TaskStatusType,
  Task,
  Worker,
  WorkerRole,
  WorkerStatus,
  FarmSetting,
  Recommendation,
  RecommendationPriority,
  FarmRecommendationReport,
  PredictionResult,
  User,
  UserRole,
  Permission
} from './livestock';

export type ReportType = 'Production' | 'Health' | 'Inventory' | 'Breeding' | 'Maintenance' | 'Compliance' | 'Financial';
export type ReportStatusType = 'Completed' | 'Processing';